import {useEffect,useRef,useState} from 'react';
import type {CSSProperties} from 'react';
import {ArrowLeft,Check,ChevronDown,ImagePlus,Layers3,Plus,RotateCcw,Save,SlidersHorizontal,Trash2,Upload,X} from 'lucide-react';
import type {Assignment,Corners,Perspective,Point,Screen,ScreenAsset,Template} from '../types';
import {perspectivePoints,renderMockup,screenPoints,validateScreen} from '../renderer/render';
import {estimateScreenPerspective,validatePerspective} from '../renderer/perspective';
import {detectGreenScreens} from './chroma';
import {saveTemplate} from '../storage/db';

type Props={onBack:()=>void;onSaved:(template:Template)=>void;initial?:Template};
type Detection={state:'idle'|'working'|'ready'|'empty'|'error';message:string};
const cornerKeys:(keyof Corners)[]=['topLeft','topRight','bottomRight','bottomLeft'];
const cornerNames=['top left','top right','bottom right','bottom left'];
const plane=(s:Screen):Perspective=>s.perspective??{tl:s.corners.topLeft,tr:s.corners.topRight,br:s.corners.bottomRight,bl:s.corners.bottomLeft};
const rotatePlane=(p:Perspective):Perspective=>({tl:p.bl,tr:p.tl,br:p.tr,bl:p.br});
const uid=()=>crypto.randomUUID();
const imageBlob=async(src:string|Blob)=>typeof src==='string'?(await fetch(src)).blob():src;
const imageSize=async(blob:Blob)=>{const image=await createImageBitmap(blob,{imageOrientation:'from-image'});const size:[number,number]=[image.width,image.height];image.close();return size;};
const thumbnail=async(blob:Blob)=>{const image=await createImageBitmap(blob);const c=document.createElement('canvas'),ratio=Math.min(1,560/Math.max(image.width,image.height));c.width=Math.round(image.width*ratio);c.height=Math.round(image.height*ratio);c.getContext('2d')!.drawImage(image,0,0,c.width,c.height);image.close();return new Promise<Blob>((resolve,reject)=>c.toBlob(v=>v?resolve(v):reject(Error('Could not create thumbnail.')),'image/webp',.84));};
const hasTransparentPixels=async(blob:Blob)=>{const image=await createImageBitmap(blob);const c=document.createElement('canvas');const scale=Math.min(1,512/Math.max(image.width,image.height));c.width=Math.max(1,Math.round(image.width*scale));c.height=Math.max(1,Math.round(image.height*scale));const ctx=c.getContext('2d',{willReadFrequently:true})!;ctx.drawImage(image,0,0,c.width,c.height);image.close();const pixels=ctx.getImageData(0,0,c.width,c.height).data;for(let i=3;i<pixels.length;i+=4)if(pixels[i]<245)return true;return false;};
const perspectiveGrid=async()=>{const c=document.createElement('canvas');c.width=600;c.height=1200;const ctx=c.getContext('2d')!;ctx.fillStyle='#17232a';ctx.fillRect(0,0,c.width,c.height);for(let y=0;y<1200;y+=75)for(let x=0;x<600;x+=75)if((x/75+y/75)%2===0){ctx.fillStyle='#243b43';ctx.fillRect(x,y,75,75);}ctx.lineWidth=2;for(let x=0;x<=600;x+=75){ctx.strokeStyle=x%150===0?'#9ee8ff':'#4f8597';ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,1200);ctx.stroke();}for(let y=0;y<=1200;y+=75){ctx.strokeStyle=y%150===0?'#9ee8ff':'#4f8597';ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(600,y);ctx.stroke();}ctx.strokeStyle='#ffb872';ctx.lineWidth=5;for(const [x,y] of [[150,225],[450,450],[300,750],[150,975]]){ctx.beginPath();ctx.arc(x,y,48,0,Math.PI*2);ctx.stroke();}ctx.strokeStyle='#ff5c5c';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(265,600);ctx.lineTo(335,600);ctx.moveTo(300,565);ctx.lineTo(300,635);ctx.stroke();ctx.fillStyle='#fff';ctx.font='bold 44px sans-serif';ctx.fillText('TOP ↑',36,65);ctx.fillText('BOTTOM ↓',36,1164);const blob=await new Promise<Blob>((resolve,reject)=>c.toBlob(v=>v?resolve(v):reject(Error('Could not create test grid.')),'image/png'));return new File([blob],'Perspective grid.png',{type:'image/png'});};

export default function Builder({onBack,onSaved,initial}:Props){
  const [master,setMaster]=useState<Blob|string|null>(initial?.masterImage??null);
  const [masterName,setMasterName]=useState(initial?.name??'');
  const [size,setSize]=useState<[number,number]>(initial?[initial.width,initial.height]:[0,0]);
  const [screens,setScreens]=useState<Screen[]>(initial?.screens??[]);
  const [selected,setSelected]=useState(0);
  const [foreground,setForeground]=useState<string|Blob|null>(initial?.foregroundLayer??null);
  const [name,setName]=useState(initial?.name??'');
  const [category,setCategory]=useState(initial?.category??'Phone');
  const [device,setDevice]=useState(initial?.device??'iPhone');
  const [style,setStyle]=useState(initial?.style??'Studio');
  const [tags,setTags]=useState(initial?.tags.join(', ')??'');
  const [tolerance,setTolerance]=useState(24);
  const [detection,setDetection]=useState<Detection>(initial?.screens.length?{state:'ready',message:`${initial.screens.length} screens detected`}:{state:'idle',message:'Upload a green-screen mockup to begin.'});
  const [advanced,setAdvanced]=useState(false);
  const [perspectiveDebug,setPerspectiveDebug]=useState(false);
  const [adjustPerspective,setAdjustPerspective]=useState(false);
  const [settingsOpen,setSettingsOpen]=useState(false);
  const [detailsOpen,setDetailsOpen]=useState(false);
  const [testImage,setTestImage]=useState<File|null>(null);
  const [individual,setIndividual]=useState<Record<string,File>>({});
  const [view,setView]=useState<'original'|'result'>('original');
  const [preview,setPreview]=useState('');
  const [rendering,setRendering]=useState(false);
  const [error,setError]=useState('');
  const [placing,setPlacing]=useState<Point[]>([]);
  const [placingActive,setPlacingActive]=useState(false);
  const [zoom,setZoom]=useState(1);
  const [masterUrl,setMasterUrl]=useState('');
  const [outlineUrls,setOutlineUrls]=useState<Record<string,string>>({});
  const fileRef=useRef<HTMLInputElement>(null),testRef=useRef<HTMLInputElement>(null),individualRef=useRef<HTMLInputElement>(null),foregroundRef=useRef<HTMLInputElement>(null),maskRef=useRef<HTMLInputElement>(null),imgRef=useRef<HTMLImageElement>(null);
  const individualTarget=useRef<string|null>(null),detectToken=useRef(0),previewToken=useRef(0),firstToleranceEffect=useRef(true);
  const drag=useRef<{screen:number;corner:keyof Corners|keyof Perspective;kind:'mask'|'perspective';before:Screen[]}|null>(null),clickedHandle=useRef(false);
  const history=useRef<Screen[][]>([]),future=useRef<Screen[][]>([]);

  useEffect(()=>{if(!master){setMasterUrl('');return;}const u=typeof master==='string'?master:URL.createObjectURL(master);setMasterUrl(u);return()=>{if(typeof master!=='string')URL.revokeObjectURL(u);};},[master]);
  useEffect(()=>{if(!foreground)return;let active=true;void imageBlob(foreground).then(hasTransparentPixels).then(valid=>{if(active&&!valid){setForeground(null);setError('Removed an opaque foreground that covered the mockup. Use a transparent PNG or WebP overlay.');}}).catch(()=>{if(active)setError('Could not read the foreground image.');});return()=>{active=false;};},[foreground]);
  useEffect(()=>{const urls:Record<string,string>={};for(const screen of screens){if(screen.outline)urls[screen.id]=typeof screen.outline==='string'?screen.outline:URL.createObjectURL(screen.outline);}setOutlineUrls(urls);return()=>{for(const screen of screens){const url=urls[screen.id];if(url&&typeof screen.outline!=='string')URL.revokeObjectURL(url);}};},[screens]);
  const commitScreens=(next:Screen[])=>{history.current.push(screens);if(history.current.length>60)history.current.shift();future.current=[];setScreens(next);};
  const undo=()=>{const previous=history.current.pop();if(previous){future.current.push(screens);setScreens(previous);setSelected(Math.min(selected,Math.max(0,previous.length-1)));}};
  const redo=()=>{const next=future.current.pop();if(next){history.current.push(screens);setScreens(next);setSelected(Math.min(selected,Math.max(0,next.length-1)));}};
  const runDetection=async(source:string|Blob,tol=tolerance)=>{
    const token=++detectToken.current;setDetection({state:'working',message:'Detecting green screens…'});setError('');setForeground(null);setPlacingActive(false);setPlacing([]);
    await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));
    try{const found=await detectGreenScreens(await imageBlob(source),tol);const estimated=await Promise.all(found.map(async screen=>{const result=await estimateScreenPerspective(screen);const fallback:Perspective={tl:screen.corners.topLeft,tr:screen.corners.topRight,br:screen.corners.bottomRight,bl:screen.corners.bottomLeft};return {...screen,perspective:result?.perspective??fallback,visibleBounds:result?.visibleBounds,visibleArea:result?.visibleArea,perspectiveStatus:result?.confident?'auto':'needs-adjustment'} as Screen;}));if(token!==detectToken.current)return;const next=estimated.length===screens.length&&screens.every(s=>s.type==='mask')?estimated.map((screen,i)=>({...screen,id:screens[i].id,label:screens[i].label})):estimated;commitScreens(next);setSelected(0);setPreview('');setIndividual({});setAdvanced(false);setAdjustPerspective(false);setDetection(found.length?{state:'ready',message:`${found.length} screen${found.length===1?'':'s'} detected`}:{state:'empty',message:'No large green screens found. Try Detection Settings or Fix Detection.'});}
    catch(e){if(token!==detectToken.current)return;setDetection({state:'error',message:'Detection could not finish.'});setError(e instanceof Error?e.message:'Could not analyze this image.');}
  };
  useEffect(()=>{if(firstToleranceEffect.current){firstToleranceEffect.current=false;const oldAutoGeometry=initial?.screens.length&&initial.screens.every(s=>s.type==='mask'&&s.outline&&(s.geometryVersion??0)<2);if(master&&(!initial?.screens.length||oldAutoGeometry))void runDetection(master,tolerance);return;}if(!master)return;const timer=setTimeout(()=>void runDetection(master,tolerance),180);return()=>clearTimeout(timer);},[tolerance]);
  const uploadMaster=async(file?:File)=>{if(!file)return;if(!/^image\/(png|jpeg|webp)$/.test(file.type)){setError('Use a PNG, JPG, or WebP master image.');return;}try{const dimensions=await imageSize(file);setMaster(file);setMasterName(file.name);setSize(dimensions);setName(file.name.replace(/\.[^.]+$/,'').replace(/[-_]/g,' '));setTestImage(null);setIndividual({});setForeground(null);setView('original');void runDetection(file,tolerance);}catch{setError('Could not read the master image.');}};
  const addScreen=()=>{if(!master){setError('Upload a master image first.');return;}setAdvanced(true);setPlacing([]);setPlacingActive(true);setError('');};
  const toPoint=(e:React.PointerEvent|React.MouseEvent):Point=>{const r=imgRef.current!.getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))];};
  const onCanvasClick=(e:React.MouseEvent)=>{if(clickedHandle.current){clickedHandle.current=false;return;}if(!placingActive||!imgRef.current)return;const r=imgRef.current.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)return;const next=[...placing,toPoint(e)];if(next.length<4){setPlacing(next);return;}const screen:Screen={id:uid(),label:`Screen ${screens.length+1}`,type:'quad',corners:{topLeft:next[0],topRight:next[1],bottomRight:next[2],bottomLeft:next[3]},fit:'cover',screenBleed:2};const issue=validateScreen(screen);if(issue){setError(`${issue} Try marking this screen again.`);setPlacing([]);return;}commitScreens([...screens,screen]);setSelected(screens.length);setPlacing([]);setPlacingActive(false);setDetection({state:'ready',message:`${screens.length+1} screens defined`});};
  const onPointerMove=(e:React.PointerEvent)=>{if(!drag.current||!imgRef.current)return;const {screen,corner,kind}=drag.current,p=toPoint(e);setScreens(previous=>previous.map((s,i)=>i===screen?(kind==='perspective'?{...s,perspective:{...plane(s),[corner]:p},perspectiveStatus:'manual'}:{...s,corners:{...s.corners,[corner]:p}}):s));};
  const onPointerUp=()=>{if(drag.current){history.current.push(drag.current.before);future.current=[];drag.current=null;}};
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setPlacingActive(false);setPlacing([]);}if(!(e.metaKey||e.ctrlKey)||e.key.toLowerCase()!=='z')return;if(['INPUT','TEXTAREA','SELECT'].includes((e.target as HTMLElement)?.tagName))return;e.preventDefault();e.shiftKey?redo():undo();};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[screens,selected]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(!(advanced||adjustPerspective)||!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))return;const active=document.activeElement as HTMLElement;if(!active?.hasAttribute('data-corner'))return;e.preventDefault();const i=Number(active.dataset.screen),corner=active.dataset.corner as keyof Corners,s=screens[i];if(!s)return;const amount=e.altKey?.25:e.shiftKey?10:1;const dx=(e.key==='ArrowLeft'?-amount:e.key==='ArrowRight'?amount:0)/size[0],dy=(e.key==='ArrowUp'?-amount:e.key==='ArrowDown'?amount:0)/size[1];if(active.dataset.kind==='perspective'){const pointKey=corner as keyof Perspective,p=plane(s)[pointKey];setScreens(previous=>previous.map((item,j)=>j===i?{...item,perspective:{...plane(item),[pointKey]:[Math.max(0,Math.min(1,p[0]+dx)),Math.max(0,Math.min(1,p[1]+dy))]},perspectiveStatus:'manual'}:item));}else{const p=s.corners[corner];setScreens(previous=>previous.map((item,j)=>j===i?{...item,corners:{...item.corners,[corner]:[Math.max(0,Math.min(1,p[0]+dx)),Math.max(0,Math.min(1,p[1]+dy))]}}:item));}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[advanced,adjustPerspective,screens,size]);
  useEffect(()=>{if(!master||!testImage||!screens.length)return;const token=++previewToken.current;setRendering(true);setError('');(async()=>{try{const assets:Record<string,ScreenAsset>={},assignments:Record<string,Assignment>={};for(const screen of screens){const file=individual[screen.id]??testImage;const [width,height]=await imageSize(file);assets[screen.id]={id:screen.id,blob:file,name:file.name,width,height,created:Date.now()};assignments[screen.id]={assetId:screen.id,transform:{fit:'cover',scale:1,x:0,y:0,rotation:0}};}const max=Math.max(Math.max(size[0],size[1]),Math.min(2800,Math.ceil(Math.max(window.innerWidth,window.innerHeight)*(window.devicePixelRatio||1))));const scale=max/Math.max(size[0],size[1]);const width=Math.round(size[0]*scale),height=Math.round(size[1]*scale);const template:Template={id:'preview',name,category,device,style,tags:[],version:1,masterImage:master,thumbnail:master,width:size[0],height:size[1],screens,foregroundLayer:foreground??undefined,createdDate:'',orientation:''};const canvas=await renderMockup({template,assets,assignments,outputWidth:width,outputHeight:height,allowUncertainPerspective:true});if(token===previewToken.current){setPreview(canvas.toDataURL('image/png'));setRendering(false);}}catch(e){if(token===previewToken.current){setRendering(false);setError(e instanceof Error?e.message:'Test render failed.');}}})();return()=>{previewToken.current++;};},[master,testImage,individual,screens,foreground,size]);
  const uploadTest=(file?:File)=>{if(!file)return;if(!screens.length){setError('Detect a screen before testing a screenshot.');return;}setTestImage(file);setIndividual({});setPerspectiveDebug(false);setView('result');};
  const showGrid=async()=>{if(!screens.length){setError('Detect a screen before testing the grid.');return;}try{uploadTest(await perspectiveGrid());setPerspectiveDebug(false);}catch(e){setError(e instanceof Error?e.message:'Could not create test grid.');}};
  const save=async()=>{if(!master){setError('Upload a master image first.');return;}if(detection.state==='working'){setError('Wait for detection to finish before saving.');return;}const issue=screens.map(validateScreen).find(Boolean)??screens.map(s=>s.type==='mask'?(s.perspective?validatePerspective(s.perspective,s.visibleBounds,s.visibleArea):'Perspective needs adjustment.'):null).find(Boolean);if(issue){setError(`Fix detection before publishing: ${issue}`);return;}if(screens.some(s=>s.type==='mask'&&s.perspectiveStatus==='needs-adjustment')){setError('Perspective needs adjustment before publishing. Open Adjust Perspective and align the four corners.');return;}const publishable=screens.length>0;try{const blob=await imageBlob(master),thumb=initial?.thumbnail&&master===initial.masterImage?initial.thumbnail:await thumbnail(blob);const template:Template={id:initial?.id??uid(),name:name.trim()||'Untitled mockup',category,device,style,tags:tags.split(',').map(x=>x.trim()).filter(Boolean),version:1,masterImage:master,thumbnail:thumb,width:size[0],height:size[1],screens,foregroundLayer:foreground??undefined,createdDate:initial?.createdDate??new Date().toISOString(),orientation:size[0]>size[1]?'Landscape':size[0]<size[1]?'Portrait':'Square',custom:true,status:publishable?'published':'draft'};await saveTemplate(template);onSaved(template);}catch(e){setError(e instanceof Error?e.message:'Could not save template.');}};
  const selectedScreen=screens[selected];const canPublish=screens.length>0&&screens.every(s=>!validateScreen(s)&&(s.type!=='mask'||s.perspectiveStatus!=='needs-adjustment'&&!!s.perspective&&!validatePerspective(s.perspective,s.visibleBounds,s.visibleArea)))&&detection.state!=='working';
  const statusLabel=detection.state==='ready'?detection.message:detection.message;

  return <div className={'builder-shell '+(advanced?'advanced':'simple')}>
    <header className="topbar"><button className="icon-button" onClick={onBack} aria-label="Back to library"><ArrowLeft size={17}/></button><div className="brand">forma<span>.</span></div><div className="top-divider"/><div className="top-title">Template Builder <span className="muted">/ {name||'New template'}</span></div><div className="top-spacer"/><span className="local-tag"><span className="status-dot"/> Private workspace</span><button className="primary-button" onClick={save}><Save size={15}/>{canPublish?'Save template':'Save draft'}</button></header>
    <input ref={testRef} type="file" hidden accept="image/png,image/jpeg,image/webp" onChange={e=>{uploadTest(e.target.files?.[0]);e.target.value='';}}/>
    <input ref={individualRef} type="file" hidden accept="image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0],id=individualTarget.current;if(file&&id){setIndividual(v=>({...v,[id]:file}));setView('result');}e.target.value='';}}/>
    <input ref={foregroundRef} type="file" hidden accept="image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void hasTransparentPixels(file).then(valid=>{if(valid){setForeground(file);setError('');}else setError('The foreground needs transparent screen cutouts. An opaque image covers the whole mockup.');}).catch(()=>setError('Could not read the foreground image.'));}}/>
    <input ref={maskRef} type="file" hidden accept="image/png" onChange={e=>{const file=e.target.files?.[0];if(file&&selectedScreen)commitScreens(screens.map((s,i)=>i===selected?{...s,mask:file,type:'mask'}:s));e.target.value='';}}/>
    <div className="builder-layout"><aside className="builder-left panel">
      <div className="panel-heading"><span>MASTER IMAGE</span><span>01</span></div>
      <button className="asset-upload" onClick={()=>fileRef.current?.click()}><ImagePlus size={22}/><strong>{master?'Replace master image':'Upload green-screen mockup'}</strong><small>PNG, JPG or WebP · stays on this device</small></button>
      <input ref={fileRef} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{void uploadMaster(e.target.files?.[0]);e.target.value='';}}/>
      {master&&<div className="asset-info"><div>{masterName}</div><span>{size[0]} × {size[1]} px</span></div>}
      <div className={'detect-summary '+detection.state}><span className="status-dot"/><strong>{statusLabel}</strong></div>
      <button className="quiet-button full" onClick={()=>master&&void runDetection(master,tolerance)} disabled={!master||detection.state==='working'}><RotateCcw size={14}/> Detect again</button>
      <details className="settings-details" open={settingsOpen} onToggle={e=>setSettingsOpen(e.currentTarget.open)}><summary>Detection Settings <ChevronDown size={14}/></summary><div className="field"><label>GREEN TOLERANCE <span>{tolerance}</span></label><input type="range" min="0" max="100" value={tolerance} onChange={e=>setTolerance(Number(e.target.value))}/></div><p className="hint">Adjust only if the detected count is wrong. Detection runs again as you move the slider.</p></details>
      {advanced&&<div className="advanced-assets"><div className="panel-heading divider"><span>MANUAL TOOLS</span></div><button className="quiet-button full" onClick={addScreen}><Plus size={15}/> Add screen by corners</button><button className="quiet-button full" onClick={()=>foregroundRef.current?.click()}><Layers3 size={15}/>{foreground?'Replace foreground':'Upload foreground'}</button>{foreground&&<button className="quiet-button full danger" onClick={()=>setForeground(null)}><Trash2 size={14}/> Remove foreground</button>}<p className="hint">Use these controls only when automatic detection needs correction.</p></div>}
      <div className="panel-bottom-note">Your source image and screenshots are processed locally.</div>
    </aside>
    <main className="builder-main"><div className="canvas-toolbar"><strong className="canvas-label">{adjustPerspective?'Adjust perspective':advanced?'Fix detection':'Preview'}</strong><div className="top-spacer"/>{testImage&&!perspectiveDebug&&!adjustPerspective&&<div className="segmented"><button className={view==='original'?'selected':''} onClick={()=>setView('original')}>Original</button><button className={view==='result'?'selected':''} onClick={()=>setView('result')}>Result</button></div>}<select className="zoom-select" value={zoom} onChange={e=>setZoom(Number(e.target.value))}><option value={.5}>50%</option><option value={1}>Fit</option><option value={2}>200%</option></select></div>
      <div className="builder-canvas" onClick={onCanvasClick} onPointerMove={onPointerMove} onPointerUp={onPointerUp}>
        {placingActive&&<div className="placement-banner" role="status"><span className="placement-step">{placing.length+1}/4</span><strong>Click {cornerNames[placing.length]}</strong><span>of the new screen</span><button onClick={e=>{e.stopPropagation();setPlacingActive(false);setPlacing([]);}}>Cancel</button></div>}
        {master?<div className="builder-art-wrap" style={{zoom,'--image-ratio':size[0]/size[1]} as CSSProperties}><img ref={imgRef} src={perspectiveDebug?masterUrl:(adjustPerspective||view==='result')&&preview?preview:masterUrl} draggable={false} alt="Mockup preview"/><svg className="builder-overlay" viewBox={`0 0 ${size[0]} ${size[1]}`} preserveAspectRatio="none" style={{display:!perspectiveDebug&&!adjustPerspective&&!advanced&&view==='result'&&preview?'none':undefined}}>
          {adjustPerspective?selectedScreen&&<g>{(()=>{const p=plane(selectedScreen),keys:(keyof Perspective)[]=['tl','tr','br','bl'];const points=keys.map(key=>[p[key][0]*size[0],p[key][1]*size[1]] as Point);return <><polygon points={points.map(v=>v.join(',')).join(' ')} className="perspective-debug-line" fill="none"/>{keys.map((key,i)=>{const [x,y]=points[i];return <g key={key} tabIndex={0} data-corner={key} data-kind="perspective" data-screen={selected} onPointerDown={e=>{e.stopPropagation();clickedHandle.current=true;drag.current={screen:selected,corner:key,kind:'perspective',before:screens};(e.target as Element).setPointerCapture(e.pointerId);}}><circle cx={x} cy={y} r={11} className="perspective-debug-dot"/><text x={x+14} y={y-12} className="perspective-debug-label">{key.toUpperCase()}</text></g>;})}</>;})()}</g>:perspectiveDebug?screens.map((screen,i)=>{const points=perspectivePoints(screen,size[0],size[1]);return <g key={screen.id}>
            <polygon points={points.map(point=>point.join(',')).join(' ')} className="perspective-debug-line" fill="none"/>
            {points.map(([x,y],corner)=><g key={corner}><circle cx={x} cy={y} r={9} className="perspective-debug-dot"/><text x={x+14} y={y-12} className="perspective-debug-label">{['TL','TR','BR','BL'][corner]} {i+1}</text></g>)}
          </g>;}):<>{screens.map((s,i)=>{const p=screenPoints({...s,screenBleed:0},size[0],size[1]);const cx=s.labelPoint&&(!advanced||selected!==i)?s.labelPoint[0]*size[0]:p.reduce((sum,v)=>sum+v[0],0)/4,cy=s.labelPoint&&(!advanced||selected!==i)?s.labelPoint[1]*size[1]:p.reduce((sum,v)=>sum+v[1],0)/4;return <g key={s.id}>{(!advanced||selected!==i)&&s.outline?outlineUrls[s.id]&&<image href={outlineUrls[s.id]} x={0} y={0} width={size[0]} height={size[1]} preserveAspectRatio="none" className="mask-outline-image"/>:<polygon points={p.map(v=>v.join(',')).join(' ')} className={advanced?'manual-outline':'detected-outline'} strokeWidth={advanced?2:1.3} fill="none"/>}<circle cx={cx} cy={cy} r={advanced?15:18} className="detected-number-bg"/><text x={cx} y={cy+5} textAnchor="middle" className="detected-number">{i+1}</text>{advanced&&selected===i&&cornerKeys.map((key,k)=>{const point=s.corners[key];return <g key={key} tabIndex={0} data-corner={key} data-screen={i} onPointerDown={e=>{e.stopPropagation();clickedHandle.current=true;setSelected(i);drag.current={screen:i,corner:key,kind:'mask',before:screens};(e.target as Element).setPointerCapture(e.pointerId);}}><circle cx={point[0]*size[0]} cy={point[1]*size[1]} r={12} fill="#fff" stroke="#29432d" strokeWidth={2}/><text x={point[0]*size[0]} y={point[1]*size[1]+4} textAnchor="middle" fontSize={11} fill="#29432d">{k+1}</text></g>;})}</g>;})}{placing.map(([x,y],i)=><g key={i}><circle cx={x*size[0]} cy={y*size[1]} r={12} fill="#fff" stroke="#29432d" strokeWidth={2}/><text x={x*size[0]} y={y*size[1]+4} textAnchor="middle" fontSize={11} fill="#29432d">{i+1}</text></g>)}</>}
        </svg></div>:<button className="empty-canvas" onClick={()=>fileRef.current?.click()}><div className="empty-icon"><Upload size={26}/></div><h2>Upload your green-screen mockup</h2><p>Displays are detected automatically. No corner marking required.</p><span className="primary-button">Choose image <Plus size={15}/></span></button>}
        {rendering&&<div className="render-badge">Rendering result…</div>}
      </div><div className="canvas-foot"><span>{detection.message}</span><span>{testImage?'Screenshot applied to all detected screens':'Your designs stay on this device'}</span></div>
    </main>
    <aside className="builder-right panel"><div className="panel-heading"><span>DETECTED SCREENS</span><span>{screens.length.toString().padStart(2,'0')}</span></div>
      <div className="detected-list">{screens.length?screens.map((s,i)=><div className={'detected-row '+(advanced&&selected===i?'active':'')} key={s.id}><span className="detected-index">{i+1}</span><div><strong>{s.label}</strong><small>{individual[s.id]?.name??(testImage?'Test screenshot applied':'Ready for screenshot')}</small></div><Check size={15}/>{testImage&&<button className="text-link" onClick={()=>{individualTarget.current=s.id;individualRef.current?.click();}}>Replace</button>}</div>):<p className="support-copy">Upload a master image to detect its green display areas.</p>}</div>
      <button className="primary-button builder-test-cta" onClick={()=>{if(!screens.length){setError('No screens detected. Adjust Detection Settings or choose Fix Detection.');return;}testRef.current?.click();}} disabled={detection.state==='working'}><ImagePlus size={15}/>{testImage?'Change test screenshot':'Test with screenshot'}</button>
      <button className="quiet-button full perspective-grid-button" onClick={()=>void showGrid()} disabled={!screens.length||detection.state==='working'}>Test perspective grid</button>
      {selectedScreen?.type==='mask'&&<div className={'validation '+(!selectedScreen.perspective||selectedScreen.perspectiveStatus==='needs-adjustment'?'warning':'ready')}>{!selectedScreen.perspective||selectedScreen.perspectiveStatus==='needs-adjustment'?'Perspective needs adjustment':selectedScreen.perspectiveStatus==='manual'?'Perspective adjusted ✓':'Perspective detected ✓'}</div>}
      {selectedScreen?.type==='mask'&&<button className="quiet-button full" onClick={()=>{setAdjustPerspective(v=>!v);setAdvanced(false);setPerspectiveDebug(false);setPlacingActive(false);setSelected(Math.max(0,selected));}}>{adjustPerspective?'Finish perspective adjustment':'Adjust Perspective'}</button>}
      {selectedScreen?.type==='mask'&&<button className="quiet-button full" onClick={()=>commitScreens(screens.map((screen,i)=>i===selected?{...screen,perspective:rotatePlane(plane(screen)),perspectiveStatus:'manual'}:screen))}>Rotate content 90°</button>}
      {testImage&&!perspectiveDebug&&<div className="segmented wide builder-view-toggle"><button className={view==='original'?'selected':''} onClick={()=>setView('original')}>Original</button><button className={view==='result'?'selected':''} onClick={()=>setView('result')}>Result</button></div>}
      {error&&<div className="builder-error" role="alert"><span>{error}</span><button onClick={()=>setError('')} aria-label="Dismiss"><X size={14}/></button></div>}
      <div className="builder-save-section"><button className="primary-button full" onClick={save}><Save size={15}/>{canPublish?'Save template':'Save draft'}</button><p>{canPublish?'Ready to add to your mockup library.':'A valid screen is needed to publish; you can save a draft.'}</p></div>
      <button className="fix-detection" onClick={()=>{setAdvanced(v=>!v);setAdjustPerspective(false);setPlacingActive(false);setPlacing([]);}}><SlidersHorizontal size={14}/>{advanced?'Done fixing':'Fix detection'}</button>
      <button className={'fix-detection perspective-debug-button'+(perspectiveDebug?' active':'')} onClick={()=>{setPerspectiveDebug(v=>!v);setAdvanced(false);setAdjustPerspective(false);setPlacingActive(false);setPlacing([]);}} disabled={!screens.length}><SlidersHorizontal size={14}/>{perspectiveDebug?'Exit Perspective Debug':'Perspective Debug'}</button>
      {advanced&&<div className="advanced-inspector"><div className="panel-heading divider"><span>MANUAL CORRECTION</span></div>{selectedScreen&&<><div className="field"><label>SELECT SCREEN</label><select value={selected} onChange={e=>setSelected(Number(e.target.value))}>{screens.map((s,i)=><option value={i} key={s.id}>{s.label}</option>)}</select></div><div className="inline-actions"><button className="quiet-button" onClick={()=>{commitScreens(screens.filter((_,i)=>i!==selected));setSelected(Math.max(0,selected-1));setPlacing([]);setPlacingActive(true);}}>Redraw region</button><button className="quiet-button danger" onClick={()=>{commitScreens(screens.filter((_,i)=>i!==selected));setSelected(Math.max(0,selected-1));}} title="Remove screen"><Trash2 size={14}/></button></div><button className="quiet-button full" onClick={()=>maskRef.current?.click()}><Layers3 size={14}/> Replace screen mask</button><p className="hint">Drag numbered corner handles on the canvas. Arrow keys move the focused handle by 1px; Shift by 10px.</p></>}</div>}
      <details className="settings-details metadata-details" open={detailsOpen} onToggle={e=>setDetailsOpen(e.currentTarget.open)}><summary>Template details <ChevronDown size={14}/></summary><div className="field"><label>NAME</label><input value={name} onChange={e=>setName(e.target.value)}/></div><div className="field"><label>CATEGORY</label><select value={category} onChange={e=>setCategory(e.target.value)}>{['Phone','Tablet','Laptop','Desktop','Browser','Poster','Print','Packaging','Social','Editorial','Experimental'].map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>DEVICE</label><select value={device} onChange={e=>setDevice(e.target.value)}>{['iPhone','Android','Tablet','Laptop','Desktop','Browser','Print','Other'].map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>STYLE</label><select value={style} onChange={e=>setStyle(e.target.value)}>{['Minimal','Editorial','Studio','Lifestyle','Abstract','Dark','Light','Colorful'].map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>TAGS</label><input value={tags} onChange={e=>setTags(e.target.value)} placeholder="green screen, phone, studio"/></div></details>
    </aside></div>
  </div>;
}
